### ISSUE TITLE
scheduler fails to start if it cannot resolve all adapter hostnames

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-syslog-drain-release#17]
We have a unique set of circumstances but I thought I would raise this issue anyway so you are aware of and issue we ran into.

We are attempting to colocate scheduler and adapter in a mini deployment.  We cannot yet use bosh links for various reasons so we statically configure a list of adapter addresses for scheduler to use.  We also deploy this vm with a dynamic ip range so we use consul host addresses for the address list.

Example scheduler config:
```
    properties:
      scalablesyslog:
        adapter:
          addrs: ["biginstance-0.node.cf.internal"]
```

If we have one instance of this vm containing both adapter and scheduler everything works fine.  However, if we scale `biginstance` to 2 nodes and statically add another adapter to the schedulers list like so:

```
    properties:
      scalablesyslog:
        adapter:
          addrs: ["biginstance-0.node.cf.internal", "biginstance-1.node.cf.internal"]
```

Then when deploying biginstance/0 the scheduler fails to start with errors like:

```
2018/06/01 17:26:53 failed to resolve adapter addrs: lookup biginstance-1.node.cf.internal on 127.0.0.1:53: no such host
```

If I use an unconnectable  static ip address instead of a host name that doesn't exist then scheduler starts fine.  So, this appears to only be an issue with needing to resolve all hosts at startup.  Perhaps adapter host name resolution can be deferred until after startup and handled the same way as if the host were unavailable?
